module:
  admin_toolbar: 0
  anonymizer: 0
  avatars: 0
  avatars_gravatar: 0
  ban: 0
  block: 0
  block_content: 0
  breakpoint: 0
  checklistapi: 0
  cidoc: 0
  cidoc_graphing: 0
  cidoc_spec: 0
  cidoc_sync: 0
  ckeditor: 0
  color_field: 0
  comment: 0
  contextual: 0
  css_editor: 0
  csv_serialization: 0
  ctools: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  editor_file: 0
  edtf: 0
  entity_reference_revisions: 0
  entity_share: 0
  entity_share_async: 0
  entity_share_client: 0
  entity_share_server: 0
  eva: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  gdpr: 0
  gdpr_dump: 0
  geocoder: 0
  geofield: 0
  google_analytics: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  inside_iframe: 0
  jsonapi: 0
  key_auth: 0
  leaflet: 0
  leaflet_views: 0
  link: 0
  medmus_cidoc: 0
  medmus_contrafacta: 0
  medmus_leaflet: 0
  medmus_medmel: 0
  medmus_share: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_facebook: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  node: 0
  oiko_app: 0
  oiko_cidoc: 0
  oiko_citation: 0
  oiko_event_basket: 0
  oiko_forum: 0
  oiko_leaflet: 0
  oiko_pleiades: 0
  oiko_prototype: 0
  oiko_sidebar: 0
  oiko_timeline: 0
  options: 0
  path: 0
  path_alias: 0
  r4032login: 0
  rdf: 0
  rest: 0
  search_api: 0
  search_api_db: 0
  serialization: 0
  sharemessage: 0
  shortcut: 0
  squid_autocomplete: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  tour_ui: 0
  tracker: 0
  unlimited_number: 0
  update: 0
  upgrade_status: 0
  user: 0
  views_bulk_operations: 0
  views_delimited_list: 0
  views_fields_on_off: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  forum: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  oiko_profile: 1000
  eu_cookie_compliance: 1001
theme:
  stable: 0
  classy: 0
  seven: 0
  oiko: 0
  medmus: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
profile: oiko_profile
