_core:
  default_config_hash: L4sRyiKH52UP6KTLHIFnKnc_7_SLelIvp-jremaWpJM
protect_all_forms: true
unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
log: false
element_name: url
time_limit: 5
expire: 300
form_settings:
  user_register_form: false
  user_pass: false
  webforms: true
  node_content_page_form: false
  node_forum_form: false
  comment_comment_forum_form: false
